### ISSUE TITLE
Suggestion; ignore failed tasks that are disabled

### ISSUE THREAD

**Issue by superbutton** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#1]
Hi

Nice work guys!

In larger environments, you would typically come across tasks that have failed, but have been marked as disabled (old versions that are waiting to be deleted, manual tasks that are run on request, etc). These should not generate emails as I see it.

**Comment by NickAkincilar** [comment]
Just upload version 1.2 that should fix this problem
