### ISSUE TITLE
Test Connection: QMC Connection Failure! Check URL or other current user credentials

### ISSUE THREAD

**Issue by laconic007** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#10]
I get this error when I plug my Qlik Sense Server URL in the setup page.
I can get test emails to send from the tool however.
The windows user configured under Task Scheduler has access to url\QMC > Tasks.
There are no Windows Firewalls
Qlik Sense Repository and Proxy services are running
I have also tried Node URL instead of https://servername
Any one else having this problem?
![error_emailalert](https://user-images.githubusercontent.com/31420814/29793048-79a2672e-8c10-11e7-9bda-dc4cc100a327.png)

**Comment by NickAkincilar** [comment]
Would you be able to send a screenshot of the settings?  How about the AD user that you are running the config app? Does that user have rights the QMC?

**Comment by laconic007** [comment]
Hi Nick,
Please take a look at this video I just captured, showing that the Windows UserName configured in the Email Alert Tool is the same user that has access to QMC as Administrator in the same box, where Qlik Sense is installed.
Let me know if I can provide any other information.   Thanks.
[QlikSenseEmailAlertTool.zip](https://github.com/NickAkincilar/QlikSense-Task-Failure-Email-Alerts/files/1270425/QlikSenseEmailAlertTool.zip)

**Comment by NickAkincilar** [comment]
@laconic007  Just looked at the video. 2 things I noticed which will cause this issue.

1. QMC virtual proxy is using forms Authentication which is prompting for web form for AD credentials. Central Virtual Proxy should be set to windows authentication with **Windows Authentication Pattern = Windows**. This would allow windows to pass AD user credentials automatically w/o user manually entering it. (This is the only way a service like email alert can communicate with QMC using APIs and it wont work until you make this change)

2. Server URL is set to https://localhost  . The URL you are using for QMC is different and the RDP name looks different as well. If the tool is running on the Sense server this is not an issue but if tool is on a machine, server name needs to match what you enter for server name in the QMC url.

**Comment by laconic007** [comment]
Hi Nick, thanks for your reply, I will try #1 today as soon as I have a window to restart services.  
Will report back!  Thanks again.

**Comment by laconic007** [comment]
Hi Nick, that worked!  I am running the Tool in the same box for simplicity's sake and using https://localhost.  Thanks for your help!

**Comment by NickAkincilar** [comment]
Glad to hear it worked.

**Comment by YosFactor** [comment]
Hi Nick, 
I have the same issue and Central Virtual Proxy set to windows authentication with Windows Authentication Pattern = Windows.
do you know what else could case this issue? 
Thanks,
Yossi
