### ISSUE TITLE
Unable to connect to server on AWS

### ISSUE THREAD

**Issue by lachlanwwells** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#4]
I have 4 separate Qlik Sense installations I manage.
2 are on hosted in a VM on Amazon Web Services and the other 2 are on-premise.

I cannot get past the test connection to QMC function on any of the AWS servers, although it works fine on the on-premise. 
"QMC Connection Failure! Check URL or the current user credentials"
They are all the same Qlik Sense version 3,2,2 running Windows Server 2012 R2
I have tried using localhost, 127.0.0.1, the hostname of the machine and still not working. I am running application as Local Administrator which has llicence allocated in Qlik
I am on 1.4 and the logging is only writing empty files
Could you please assist?

**Comment by NickAkincilar** [comment]
The tool uses Active directory for authentication to QMC which currently is the only way you can authenticate. The AD user has to have admin rights to QMC to be able to view tasks details. My guess is your on-prem servers authenticate you via AD but the AWS server are not. One method would be to install the tool locally on the AWS sense servers and use a local windows qlik admin account to run the tool
