### ISSUE TITLE
Configuration problems, test email error message

### ISSUE THREAD

**Issue by scottduthie** [NickAkincilar/QlikSense-Task-Failure-Email-Alerts#6]
Hi Nick,

Great extension, it's exactly what we need!
I am having some problems getting things configured and generating the test email though, see screenshot below.

![sc1](https://cloud.githubusercontent.com/assets/28118019/26628772/47dff454-45f7-11e7-9d52-a0111dd9ea88.png)

![sc2](https://cloud.githubusercontent.com/assets/28118019/26628847/9fbab3b2-45f7-11e7-937f-f1469578dc1a.png)

We have tested the connection and set the gmail settings correctly. We have changed the port to 465 for SSL.

Any ideas on what to look at next?

Much appreciated,

Scott.

**Comment by NickAkincilar** [comment]
it looks like you are using port 465 with SSL. Port 465 is used for non-SSL connections. For SSL, you would need to use port 587.

Also make sure to turn ON the less secure option to allow SMTP connections.
http://www.google.com/settings/security/lesssecureapps

**Comment by scottduthie** [comment]
Hi Nick,

Thanks for coming back to me, much appreciated.
I have turned on the less secure option in the gmail account and tried using port 587 but receive the following error message.......
![image](https://cloud.githubusercontent.com/assets/28118019/26719908/3216177e-477e-11e7-8233-9ddd824bc09d.png)

Any other ideas on next steps?

Many Thanks,

Scott.

**Comment by NickAkincilar** [comment]
Based on some research if could be few things such as time zone on the server not matching the google servers that you created the gmail account. Did you try to login to gmail from the machine that the email app is installed?

If not, is there any other non-gmail email server that you can try?

This link should show you computers logging in to account and time zones.
https://security.google.com/settings/security/activity

**Comment by scottduthie** [comment]
Thanks for the above suggestion, you were spot on with the gmail account being out of sync with the server the app is installed on. The test email now send sends as expected.

We're still struggling to get the automated email sent on the failure of a task in the QMC. We have linked the QS service account to the extension and have set up the custom property and linked this to the scheduled task inline with you documentation. The 'Task Log' and 'Send History' log file remains empty. Is there an 'executable' that is launched when the task fails that creates a log file, or some way we can try and diagnose why the automated email is not sending? 

Any suggestions would be much appreciated. Thanks for the help so far!

**Comment by NickAkincilar** [comment]
If the task log is empty, I am guessing it is not running or not being triggered.
1- Make sure windows user name listed in the app has TASK rights. Login to QMC from that machine with that account and view tasks to confirm.

2- Make sure to hit SAVE SETTINGS.

3- Make sure to click ADD/UPDATE Scheduler button. (This creates a windows scheduler task using the windows name listed in the app to run the task automatically at specific intervals.)

Alternatively you can open Windows Task Scheduler and you should see a task called "QlikSense Email Alert - (Auto)". You can look a the last run and next run date/times to see if the system has run the app or when it will execute next.

**Comment by NickAkincilar** [comment]
One final thing. Close the configuration app/window.  If it is open while the task is running, you may have issues with empty log files.

**Comment by scottduthie** [comment]
Hi Nick,

Thanks for the above note, I now have the email alerts up and running, although I'm not 100% exactly what it was that fixed things! I had been using the QS server service account in the extension configuration, when I changed to using the 'Administrator' account (the one that installed QS in the first place) all started working fine. This is likely related to something odd we have done in our server and QMC.

Thanks for your help on this, it's much appreciated!
